### ISSUE TITLE
Cleanup management for Releases 

### ISSUE THREAD

**Issue by reflexxion** [CORE4/fulmar#1]
Releases aren't cleaned up so they'll stay there forever.
Please implement some cleanup logic.

**Comment by kayssun** [comment]
With Fulmar 1.x you can set the option `limit_releases: 5` within a target with `type: rsync_with_versions`. 
Default ist 10.
Then you can run `fulmar versions:clean:live` to delete all but the latest 5 versions. Calling `file_sync.publish` within a task will not clean up versions automatically. If you always want to clean up when deploying you can add the cleanup task in the deployment task. I would recommend not to do so, destructive tasks should always be called explicitly.

These options might change with Fulmar 2.

**Comment by reflexxion** [comment]
Ok, thanks =)
